Added sample pod

diff --git a/iOS Class Guard/obfuscate_project b/iOS Class Guard/obfuscate_project
--- a/iOS Class Guard/obfuscate_project
+++ b/iOS Class Guard/obfuscate_project
@@ -1,76 +1,120 @@
 #!/bin/bash
 
-set -xe
+set -e
 
-PROJECT="iOSClassGuard OpenSourceBar.xcodeproj"
-SCHEME=ExampleBankingApp
-TARGET="iOSClassGuard OpenSourceBar"
+# General build options
+WORKSPACE="iOSClassGuard OpenSourceBar.xcworkspace"
+# PROJECT=YourProject.xcodeproj
+SCHEME="ExampleBankingApp"
 CONFIGURATION=Release
-OBFUSCATION_SDK=iphonesimulator
-SDK=iphoneos
 
-git reset --hard
-git clean -fdx
+# Additional build options
+XCODEBUILD_OPTS=""
+CLASS_GUARD_OPTS="-i IgnoredSymbol -F !ExcludedClass"
 
-rm -rf headers headers.obf build build.obf
+# In case of using Xcode >= 6 and SDK >= 8
+CLASS_GUARD_OPTS_SDK="--sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
+# CLASS_GUARD_OPTS_SDK="$CLASS_GUARD_OPTS_SDK --sdk-ios iphonesimulator"
 
-if ! which ios-class-guard; then
-	brew install ios-class-guard
-fi
+####################################################
+# BUILD SCRIPT STARTS HERE
+####################################################
 
-if ! which xcpretty; then
-	gem install xcpretty
-fi
+# Just in case
+echo "WARNING: This will wipe all your not commited changes in your repository"
+echo "Press Ctrl-C to Cancel or Enter to proceed."
+read
 
-if ! which class-dump; then
-	brew install class-dump
-fi
+function echo_and_run() {
+    echo "$@"
+    "$@"
+}
 
-# Build project to fetch symbols
-xcodebuild \
-	-project "$PROJECT" \
-	-scheme "$SCHEME" \
-	-configuration "$CONFIGURATION" \
-	-sdk "$OBFUSCATION_SDK" \
-	clean build \
-	OBJROOT=build/ \
-	SYMROOT=build/ |\
-	xcpretty -c
+# Jump to directory where obfuscate script is located
+pushd $(dirname $0)
 
+# # Symbols file path
 SYMBOLS_FILE="$PWD/symbols.h"
 
-find . -name '*-Prefix.pch' -exec sed -i .bak '1i\
+# Clean current workspace
+echo_and_run git reset --hard
+echo_and_run git clean -fdx
+
+# Just in case: wipe build/
+rm -rf build/ build.obf/ headers/ headers.obf/
+
+# Automatically detect PODS
+[[ -f Podfile ]] && [[ ! -f Pods/Manifest.lock ]] && pod install
+[[ -f Pods/Pods.xcodeproj/project.pbxproj ]] && CLASS_GUARD_OPTS="$CLASS_GUARD_OPTS -P Pods/Pods.xcodeproj/project.pbxproj"
+
+echo_and_run xcodebuild \
+	-workspace "$WORKSPACE" \
+	-scheme $SCHEME \
+	-configuration $CONFIGURATION \
+	-sdk iphonesimulator \
+    clean build \
+    OBJROOT="$PWD/build/" \
+    SYMROOT="$PWD/build/" |\
+    xcpretty
+
+# Obfuscate project
+appsNumber=0;
+while read app
+do
+    if ((appsNumber > 0))
+    then
+        echo ""
+        echo ""
+        echo "You cannot use this tool when there is more than one .app file in products. Otherwise, only the first one will be used for obfuscation."
+        echo ""
+        echo ""
+        exit
+    fi
+    ((appsNumber+=1))
+
+    TARGET=$(basename "$app" .app)
+    
+    echo_and_run class-dump -H -o headers "$app/$TARGET"
+
+	echo "Obfuscating $TARGET in $app..."
+    echo_and_run ios-class-guard \
+        $CLASS_GUARD_OPTS_SDK \
+        $CLASS_GUARD_OPTS \
+        -O "$SYMBOLS_FILE" \
+        "$app/$TARGET"
+done < <(find build/ -name '*.app')
+
+# Insert SYMBOLS_FILE to all .pch found in project
+echo_and_run find . -iname '*-Prefix.pch' -exec sed -i .bak '1i\
 '"#import \"$SYMBOLS_FILE\"
 " "{}" \;
 
-class-dump -H -o headers "build/$CONFIGURATION-$OBFUSCATION_SDK/$TARGET.app/$TARGET"
+echo_and_run xcodebuild \
+	-workspace "$WORKSPACE" \
+	-scheme $SCHEME \
+	-configuration $CONFIGURATION \
+	-sdk iphonesimulator \
+    clean build \
+    OBJROOT="$PWD/build.obf/" \
+    SYMROOT="$PWD/build.obf/" |\
+    xcpretty
 
-DEVELOPER_DIR="$(xcode-select -p)"
+appsNumber=0;
+while read app
+do
+    if ((appsNumber > 0))
+    then
+        echo ""
+        echo ""
+        echo "You cannot use this tool when there is more than one .app file in products. Otherwise, only the first one will be used for obfuscation."
+        echo ""
+        echo ""
+        exit
+    fi
+    ((appsNumber+=1))
 
-SDK_DIR="$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
-[[ ! -e "$SDK_DIR" ]] && SDK_DIR="$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk"
-[[ ! -e "$SDK_DIR" ]] && SDK_DIR="$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk"
-[[ ! -e "$SDK_DIR" ]] && SDK_DIR="$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk"
-[[ ! -e "$SDK_DIR" ]] && SDK_DIR="$DEVELOPER_DIR/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk"
-[[ ! -d "$SDK_DIR" ]] && echo "$SDK_DIR doesn't exist" && exit 1
+    TARGET=$(basename "$app" .app)
+    
+    echo_and_run class-dump -H -o headers.obf "$app/$TARGET"
 
-echo "Using $SDK_DIR..."
-
-# Obfuscate project
-ios-class-guard \
-	--sdk-root "$SDK_DIR" \
-	-O symbols.h \
-	"build/$CONFIGURATION-$OBFUSCATION_SDK/$TARGET.app/$TARGET"
-
-# Build project to fetch symbols
-xcodebuild \
-	-project "$PROJECT" \
-	-scheme "$SCHEME" \
-	-configuration "$CONFIGURATION" \
-	-sdk "$SDK" \
-	clean build \
-	OBJROOT=build.obf/ \
-	SYMROOT=build.obf/ |\
-	xcpretty -c
-
-class-dump -H -o headers.obf "build.obf/$CONFIGURATION-$SDK/$TARGET.app/$TARGET"
+done < <(find build.obf/ -name '*.app')
